import assets from "./assets";

const NFTData = [
  // {
  //   id: "NFT-01",
  //   name: "Donut animation",
  //   creator: "Jascuas",
  //   price: 4.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   path: assets.nft01,
  //   type: "video",
  //   orientation: "portrait",
  //   bids: [
  //     {
  //       id: "BID-11",
  //       name: "iDarkDestiny",
  //       price: 4.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-12",
  //       name: "Noa",
  //       price: 4.5,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-13",
  //       name: "Jandrid",
  //       price: 4.75,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-02",
  //   name: "Wildfire",
  //   creator: "Jascuas",
  //   price: 7.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
  //   path: assets.nft02,
  //   type: "video",
  //   orientation: "landscape",
  //   bids: [
  //     {
  //       id: "BID-21",
  //       name: "Jandrid",
  //       price: 7.05,
  //       image: assets.person04,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //   ],
  // },
  {
    id: "NFT-03",
    name: "Portals to another dimension",
    creator: "Jascuas",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
      path: assets.nft03,
      type: "image",
      orientation: "landscape",
    bids: [
      {
        id: "BID-31",
        name: "iDarkDestiny",
        price: 95.25,
        image: assets.person02,
        date: "December 12, 2019 at 12:10 PM",
      },
      {
        id: "BID-32",
        name: "Noa",
        price: 95.5,
        image: assets.person03,
        date: "December 27, 2019 at 1:50 PM",
      },
    ],
  },
  // {
  //   id: "NFT-04",
  //   name: "Satisfying animation",
  //   creator: "Jascuas",
  //   price: 54.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur.",
  //     path: assets.nft04,
  //     type: "video",
  //     orientation: "portrait",
  //   bids: [
  //     {
  //       id: "BID-41",
  //       name: "iDarkDestiny",
  //       price: 56.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-42",
  //       name: "Noa",
  //       price: 54.25,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-43",
  //       name: "Jandrid",
  //       price: 55.15,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-44",
  //       name: "iDarkDestiny",
  //       price: 54.15,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-05",
  //   name: "Scifi Enviroment",
  //   creator: "Jascuas",
  //   price: 10.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //     path: assets.nft05,
  //     type: "video",
  //     orientation: "landscape",
  //   bids: [
  //     {
  //       id: "BID-51",
  //       name: "iDarkDestiny",
  //       price: 10.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-06",
  //   name: "Sun order",
  //   creator: "Jascuas",
  //   price: 20.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
  //     path: assets.nft06,
  //     type: "image",
  //     orientation: "landscape",
  //   bids: [
  //     {
  //       id: "BID-61",
  //       name: "iDarkDestiny",
  //       price: 20.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-62",
  //       name: "Noa",
  //       price: 20.5,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-63",
  //       name: "Jandrid",
  //       price: 20.75,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-64",
  //       name: "iDarkDestiny",
  //       price: 21.25,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-65",
  //       name: "iDarkDestiny",
  //       price: 7.25,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-07",
  //   name: "NFT Card",
  //   creator: "Jascuas",
  //   price: 18.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
  //     path: assets.nft07,
  //     type: "video",
  //     orientation: "portrait",
  //   bids: [],
  // },
  {
    id: "NFT-08",
    name: "Donut Eater #01",
    creator: "Jascuas",
    price: 4.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
    path: assets.nft08,
    type: "video",
    orientation: "portrait",
    bids: [
      {
        id: "BID-11",
        name: "iDarkDestiny",
        price: 4.25,
        image: assets.person02,
        date: "December 12, 2019 at 12:10 PM",
      },
      {
        id: "BID-12",
        name: "Noa",
        price: 4.5,
        image: assets.person03,
        date: "December 27, 2019 at 1:50 PM",
      },
      {
        id: "BID-13",
        name: "Jandrid",
        price: 4.75,
        image: assets.person04,
        date: "December 31, 2019 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-09",
    name: "Donut Eater #02",
    creator: "Jascuas",
    price: 4.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
    path: assets.nft09,
    type: "video",
    orientation: "portrait",
    bids: [
      {
        id: "BID-21",
        name: "iDarkDestiny",
        price: 7.05,
        image: assets.person04,
        date: "December 12, 2019 at 12:10 PM",
      },
    ],
  },
  {
    id: "NFT-10",
    name: "Donut Eater #03",
    creator: "Jascuas",
    price: 4.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
    path: assets.nft10,
    type: "video",
    orientation: "portrait",
    bids: [
      {
        id: "BID-31",
        name: "iDarkDestiny",
        price: 95.25,
        image: assets.person02,
        date: "December 12, 2019 at 12:10 PM",
      },
      {
        id: "BID-32",
        name: "Noa",
        price: 95.5,
        image: assets.person03,
        date: "December 27, 2019 at 1:50 PM",
      },
    ],
  },
  {
    id: "NFT-11",
    name: "Donut Eater #04",
    creator: "Jascuas",
    price: 4.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
    path: assets.nft11,
    type: "video",
    orientation: "portrait",
    bids: [
      {
        id: "BID-41",
        name: "iDarkDestiny",
        price: 56.25,
        image: assets.person02,
        date: "December 12, 2019 at 12:10 PM",
      },
      {
        id: "BID-42",
        name: "Noa",
        price: 54.25,
        image: assets.person03,
        date: "December 27, 2019 at 1:50 PM",
      },
      {
        id: "BID-43",
        name: "Jandrid",
        price: 55.15,
        image: assets.person04,
        date: "December 31, 2019 at 3:50 PM",
      },
      {
        id: "BID-44",
        name: "iDarkDestiny",
        price: 54.15,
        image: assets.person02,
        date: "December 31, 2019 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-12",
    name: "Donut Eater #05",
    creator: "Jascuas",
    price: 4.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
    path: assets.nft12,
    type: "video",
    orientation: "portrait",
    bids: [
      {
        id: "BID-51",
        name: "iDarkDestiny",
        price: 10.25,
        image: assets.person02,
        date: "December 12, 2019 at 12:10 PM",
      },
    ],
  },
  // {
  //   id: "NFT-13",
  //   name: "Donut Eater #06",
  //   creator: "Jascuas",
  //   price: 4.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   path: assets.nft13,
  //   type: "video",
  //   orientation: "portrait",
  //   bids: [
  //     {
  //       id: "BID-61",
  //       name: "iDarkDestiny",
  //       price: 20.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-62",
  //       name: "Noa",
  //       price: 20.5,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-63",
  //       name: "Jandrid",
  //       price: 20.75,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-64",
  //       name: "iDarkDestiny",
  //       price: 21.25,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-65",
  //       name: "iDarkDestiny",
  //       price: 7.25,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-14",
  //   name: "Donut Eater #07",
  //   creator: "Jascuas",
  //   price: 4.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   path: assets.nft14,
  //   type: "video",
  //   orientation: "portrait",
  //   bids: [],
  // },
  // {
  //   id: "NFT-15",
  //   name: "Donut Eater #08",
  //   creator: "Jascuas",
  //   price: 4.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   path: assets.nft15,
  //   type: "video",
  //   orientation: "portrait",
  //   bids: [
  //     {
  //       id: "BID-21",
  //       name: "iDarkDestiny",
  //       price: 7.05,
  //       image: assets.person04,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-16",
  //   name: "Donut Eater #09",
  //   creator: "Jascuas",
  //   price: 4.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   path: assets.nft16,
  //   type: "video",
  //   orientation: "portrait",
  //   bids: [
  //     {
  //       id: "BID-31",
  //       name: "iDarkDestiny",
  //       price: 95.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-32",
  //       name: "Noa",
  //       price: 95.5,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-17",
  //   name: "Donut Eater #10",
  //   creator: "Jascuas",
  //   price: 4.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   path: assets.nft17,
  //   type: "video",
  //   orientation: "portrait",
  //   bids: [
  //     {
  //       id: "BID-41",
  //       name: "iDarkDestiny",
  //       price: 56.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-42",
  //       name: "Noa",
  //       price: 54.25,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-43",
  //       name: "Jandrid",
  //       price: 55.15,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-44",
  //       name: "iDarkDestiny",
  //       price: 54.15,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
];

export { NFTData };
